export const MOCK_DATA = [
  {
    creator_id: "pranjal_kamra",
    creator_name: "Pranjal Kamra",
    overall_accuracy_score: 71,
    total_predictions: 31,
    category_scores: { stocks: 78, crypto: 52, macro: 68, index: 74 },
    predictions: [
      {
        prediction_id: "pranjal_001",
        video_url: "https://youtube.com/watch?v=example1",
        video_title: "Value Stocks to Watch 2023",
        video_date: "2023-01-20",
        timestamp_in_video: "08:10",
        exact_quote: "Reliance will be a strong buy at current levels and deliver 15% returns by year end",
        asset_name: "Reliance Industries",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hedged",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 2450,
        accuracy_score: 74,
        verdict: "Correct — Reliance gained 12% over the period, slightly below predicted 15%",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "pranjal_002",
        video_url: "https://youtube.com/watch?v=example2",
        video_title: "IT Sector Deep Dive 2023",
        video_date: "2023-02-15",
        timestamp_in_video: "12:45",
        exact_quote: "TCS will outperform Infosys in 2023 due to stronger deal pipeline",
        asset_name: "TCS",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 3280,
        accuracy_score: 81,
        verdict: "Correct — TCS outperformed Infosys by 8% over the year",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "pranjal_003",
        video_url: "https://youtube.com/watch?v=example3",
        video_title: "Crypto Market Reality Check",
        video_date: "2023-03-10",
        timestamp_in_video: "06:20",
        exact_quote: "Bitcoin will not cross 35,000 dollars before June 2023",
        asset_name: "Bitcoin",
        asset_type: "crypto",
        predicted_direction: "down",
        predicted_value: 35000,
        predicted_by_date: "2023-06-30",
        confidence_language: "hard_claim",
        actual_value: 30000,
        actual_direction: "down",
        price_on_prediction_date: 22000,
        accuracy_score: 78,
        verdict: "Correct — Bitcoin stayed below 35k through June 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "pranjal_004",
        video_url: "https://youtube.com/watch?v=example4",
        video_title: "Nifty 2023 Outlook",
        video_date: "2023-01-05",
        timestamp_in_video: "03:15",
        exact_quote: "Nifty will consolidate between 17,000 and 19,000 for most of 2023",
        asset_name: "Nifty 50",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: 19000,
        predicted_by_date: "2023-12-31",
        confidence_language: "hedged",
        actual_value: 21200,
        actual_direction: "up",
        price_on_prediction_date: 17800,
        accuracy_score: 55,
        verdict: "Partially wrong — Nifty broke above 19,000 and reached 21,200",
        failure_reason: "Underestimated bullish momentum in H2 2023",
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "pranjal_005",
        video_url: "https://youtube.com/watch?v=example5",
        video_title: "Banking Sector Picks 2023",
        video_date: "2023-04-12",
        timestamp_in_video: "09:30",
        exact_quote: "HDFC Bank merger will create massive value and stock will hit 1800 by December",
        asset_name: "HDFC Bank",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: 1800,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 1650,
        actual_direction: "up",
        price_on_prediction_date: 1620,
        accuracy_score: 68,
        verdict: "Directionally correct but missed target of 1800, closed at 1650",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      }
    ]
  },
  {
    creator_id: "akshat_shrivastava",
    creator_name: "Akshat Shrivastava",
    overall_accuracy_score: 63,
    total_predictions: 47,
    category_scores: { stocks: 71, crypto: 43, macro: 60, index: 68 },
    predictions: [
      {
        prediction_id: "akshat_001",
        video_url: "https://youtube.com/watch?v=akshat1",
        video_title: "My 2023 Market Predictions",
        video_date: "2023-01-15",
        timestamp_in_video: "04:32",
        exact_quote: "Nifty will touch 22,000 by December 2023",
        asset_name: "Nifty 50",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: 22000,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 21200,
        actual_direction: "up",
        price_on_prediction_date: 18500,
        accuracy_score: 72,
        verdict: "Directionally correct, missed target by 3.8%",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "akshat_002",
        video_url: "https://youtube.com/watch?v=akshat2",
        video_title: "Crypto Portfolio Strategy 2023",
        video_date: "2023-02-01",
        timestamp_in_video: "15:20",
        exact_quote: "Ethereum will hit 3000 dollars by end of 2023, it is inevitable",
        asset_name: "Ethereum",
        asset_type: "crypto",
        predicted_direction: "up",
        predicted_value: 3000,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 2200,
        actual_direction: "up",
        price_on_prediction_date: 1600,
        accuracy_score: 48,
        verdict: "Directionally correct but missed 3000 target significantly, closed at 2200",
        failure_reason: "Overestimated ETH recovery speed post-merge",
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "akshat_003",
        video_url: "https://youtube.com/watch?v=akshat3",
        video_title: "Small Cap Opportunities 2023",
        video_date: "2023-03-20",
        timestamp_in_video: "22:10",
        exact_quote: "Small cap index will underperform large caps in 2023 due to global uncertainty",
        asset_name: "Nifty Small Cap 100",
        asset_type: "index",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 9800,
        accuracy_score: 22,
        verdict: "Wrong — small caps significantly outperformed large caps in 2023",
        failure_reason: "Underestimated domestic retail investor appetite for small caps",
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "akshat_004",
        video_url: "https://youtube.com/watch?v=akshat4",
        video_title: "US Recession Impact on India",
        video_date: "2023-04-05",
        timestamp_in_video: "08:45",
        exact_quote: "If US enters recession, Indian IT stocks will fall 20 to 30 percent",
        asset_name: "Nifty IT",
        asset_type: "index",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hedged",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 28000,
        accuracy_score: 35,
        verdict: "Wrong direction — IT index recovered strongly despite US slowdown fears",
        failure_reason: "US soft landing scenario not accounted for",
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      },
      {
        prediction_id: "akshat_005",
        video_url: "https://youtube.com/watch?v=akshat5",
        video_title: "PSU Stocks Deep Dive",
        video_date: "2023-05-18",
        timestamp_in_video: "11:30",
        exact_quote: "PSU banks are massively undervalued, SBI will touch 700 by year end",
        asset_name: "SBI",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: 700,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 620,
        actual_direction: "up",
        price_on_prediction_date: 520,
        accuracy_score: 71,
        verdict: "Directionally correct, SBI rose strongly but fell short of 700 target",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      }
    ]
  },
  {
    creator_id: "rachana_ranade",
    creator_name: "CA Rachana Ranade",
    overall_accuracy_score: 58,
    total_predictions: 29,
    category_scores: { stocks: 65, crypto: 32, macro: 55, index: 62 },
    predictions: [
      {
        prediction_id: "rachana_001",
        video_url: "https://youtube.com/watch?v=rachana1",
        video_title: "Stock Market Outlook 2023",
        video_date: "2023-02-10",
        timestamp_in_video: "02:15",
        exact_quote: "HDFC Bank will outperform the broader market in the first half of 2023",
        asset_name: "HDFC Bank",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-06-30",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 1580,
        accuracy_score: 65,
        verdict: "Correct — HDFC Bank gained 8% vs Nifty's 5% in H1 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "rachana_002",
        video_url: "https://youtube.com/watch?v=rachana2",
        video_title: "Should You Invest in Crypto in 2023",
        video_date: "2023-01-25",
        timestamp_in_video: "18:40",
        exact_quote: "I would not recommend crypto to anyone right now, Bitcoin could go to 10,000",
        asset_name: "Bitcoin",
        asset_type: "crypto",
        predicted_direction: "down",
        predicted_value: 10000,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 42000,
        actual_direction: "up",
        price_on_prediction_date: 23000,
        accuracy_score: 8,
        verdict: "Completely wrong — Bitcoin nearly doubled to 42,000 by year end",
        failure_reason: "Failed to anticipate ETF approval momentum and institutional buying",
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "rachana_003",
        video_url: "https://youtube.com/watch?v=rachana3",
        video_title: "Pharma Sector Analysis",
        video_date: "2023-03-15",
        timestamp_in_video: "14:22",
        exact_quote: "Pharma sector will make a comeback in 2023, Sun Pharma is my top pick",
        asset_name: "Sun Pharma",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 980,
        accuracy_score: 77,
        verdict: "Correct — Sun Pharma gained 22% through 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "rachana_004",
        video_url: "https://youtube.com/watch?v=rachana4",
        video_title: "Interest Rate Impact on Markets",
        video_date: "2023-06-01",
        timestamp_in_video: "07:55",
        exact_quote: "RBI will cut rates at least twice before end of 2023",
        asset_name: "RBI Rate",
        asset_type: "macro",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "neutral",
        price_on_prediction_date: null,
        accuracy_score: 15,
        verdict: "Wrong — RBI held rates steady throughout 2023, no cuts made",
        failure_reason: "Inflation remained sticky, preventing any rate cuts",
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      },
      {
        prediction_id: "rachana_005",
        video_url: "https://youtube.com/watch?v=rachana5",
        video_title: "Mid Cap Gems for 2023",
        video_date: "2023-04-20",
        timestamp_in_video: "19:10",
        exact_quote: "Mid cap funds will give better returns than large caps over next 12 months",
        asset_name: "Nifty Midcap 100",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2024-04-20",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 32000,
        accuracy_score: 82,
        verdict: "Correct — Midcap 100 outperformed Nifty 50 by 11% over the period",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "index"
      }
    ]
  },
  {
    creator_id: "vivek_bajaj",
    creator_name: "Vivek Bajaj",
    overall_accuracy_score: 55,
    total_predictions: 38,
    category_scores: { stocks: 62, crypto: 38, macro: 50, index: 60 },
    predictions: [
      {
        prediction_id: "vivek_001",
        video_url: "https://youtube.com/watch?v=vivek1",
        video_title: "Market Analysis 2023",
        video_date: "2023-04-01",
        timestamp_in_video: "03:22",
        exact_quote: "Sensex will reach 65,000 before year end, the bull run is not over",
        asset_name: "Sensex",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: 65000,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 63000,
        actual_direction: "up",
        price_on_prediction_date: 58500,
        accuracy_score: 68,
        verdict: "Directionally correct, came within 3% of 65,000 target",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "vivek_002",
        video_url: "https://youtube.com/watch?v=vivek2",
        video_title: "Options Strategy for Volatile Markets",
        video_date: "2023-02-20",
        timestamp_in_video: "28:15",
        exact_quote: "Volatility index India VIX will spike above 20 in the next 3 months",
        asset_name: "India VIX",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: 20,
        predicted_by_date: "2023-05-20",
        confidence_language: "moderate",
        actual_value: 14,
        actual_direction: "down",
        price_on_prediction_date: 13,
        accuracy_score: 18,
        verdict: "Wrong — VIX stayed calm and actually decreased through May 2023",
        failure_reason: "Markets remained surprisingly stable despite global headwinds",
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "vivek_003",
        video_url: "https://youtube.com/watch?v=vivek3",
        video_title: "Auto Sector Opportunity",
        video_date: "2023-05-10",
        timestamp_in_video: "11:05",
        exact_quote: "Maruti Suzuki will benefit massively from EV transition delay and cross 10,000",
        asset_name: "Maruti Suzuki",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: 10000,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 10500,
        actual_direction: "up",
        price_on_prediction_date: 8600,
        accuracy_score: 88,
        verdict: "Correct — Maruti crossed 10,000 and hit 10,500 by December 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "vivek_004",
        video_url: "https://youtube.com/watch?v=vivek4",
        video_title: "Crypto is Dead?",
        video_date: "2023-03-01",
        timestamp_in_video: "05:30",
        exact_quote: "Crypto winter will last through 2023, do not buy altcoins",
        asset_name: "Altcoins",
        asset_type: "crypto",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: null,
        accuracy_score: 20,
        verdict: "Wrong — altcoins had a strong recovery rally in Q4 2023",
        failure_reason: "Bitcoin ETF narrative lifted entire crypto market",
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "vivek_005",
        video_url: "https://youtube.com/watch?v=vivek5",
        video_title: "FII vs DII Battle 2023",
        video_date: "2023-07-15",
        timestamp_in_video: "16:40",
        exact_quote: "Domestic institutional money will keep markets supported even if FIIs sell",
        asset_name: "Nifty 50",
        asset_type: "macro",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hedged",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 19500,
        accuracy_score: 79,
        verdict: "Correct — DII buying offset FII selling and markets stayed resilient",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      }
    ]
  },
  {
    creator_id: "ankur_warikoo",
    creator_name: "Ankur Warikoo",
    overall_accuracy_score: 49,
    total_predictions: 21,
    category_scores: { stocks: 52, crypto: 35, macro: 48, index: 55 },
    predictions: [
      {
        prediction_id: "ankur_001",
        video_url: "https://youtube.com/watch?v=ankur1",
        video_title: "My Crypto Predictions 2023",
        video_date: "2023-03-05",
        timestamp_in_video: "06:45",
        exact_quote: "Bitcoin will cross 40,000 dollars by mid 2023, the bottom is in",
        asset_name: "Bitcoin",
        asset_type: "crypto",
        predicted_direction: "up",
        predicted_value: 40000,
        predicted_by_date: "2023-06-30",
        confidence_language: "hard_claim",
        actual_value: 30000,
        actual_direction: "up",
        price_on_prediction_date: 22000,
        accuracy_score: 38,
        verdict: "Directionally correct but missed 40k target badly — Bitcoin was at 30k by June",
        failure_reason: "Overestimated recovery speed post-FTX collapse",
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "ankur_002",
        video_url: "https://youtube.com/watch?v=ankur2",
        video_title: "Should You Buy Index Funds Now",
        video_date: "2023-01-30",
        timestamp_in_video: "09:20",
        exact_quote: "Index fund investors should stay patient, Nifty will reward them by end of year",
        asset_name: "Nifty 50",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hedged",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 18000,
        accuracy_score: 75,
        verdict: "Correct — Nifty delivered 18% returns through 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "ankur_003",
        video_url: "https://youtube.com/watch?v=ankur3",
        video_title: "Startup Ecosystem 2023",
        video_date: "2023-04-18",
        timestamp_in_video: "21:00",
        exact_quote: "Startup valuations will correct another 40 to 50 percent before recovery",
        asset_name: "Startup Ecosystem",
        asset_type: "macro",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "down",
        price_on_prediction_date: null,
        accuracy_score: 62,
        verdict: "Largely correct — startup funding winter continued through 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      },
      {
        prediction_id: "ankur_004",
        video_url: "https://youtube.com/watch?v=ankur4",
        video_title: "Zomato vs Swiggy Investment Case",
        video_date: "2023-06-10",
        timestamp_in_video: "14:30",
        exact_quote: "Zomato will be profitable by Q4 2023 and stock will cross 100 rupees",
        asset_name: "Zomato",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: 100,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 115,
        actual_direction: "up",
        price_on_prediction_date: 62,
        accuracy_score: 91,
        verdict: "Spot on — Zomato turned profitable and stock crossed 115 by December",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "ankur_005",
        video_url: "https://youtube.com/watch?v=ankur5",
        video_title: "Web3 is Overhyped",
        video_date: "2023-02-22",
        timestamp_in_video: "31:15",
        exact_quote: "NFTs are dead and will never recover to 2021 levels in our lifetime",
        asset_name: "NFT Market",
        asset_type: "crypto",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "down",
        price_on_prediction_date: null,
        accuracy_score: 85,
        verdict: "Correct — NFT volumes collapsed and never recovered through 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      }
    ]
  },
  {
    creator_id: "shankar_nath",
    creator_name: "Shankar Nath",
    overall_accuracy_score: 38,
    total_predictions: 19,
    category_scores: { stocks: 42, crypto: 28, macro: 38, index: 41 },
    predictions: [
      {
        prediction_id: "shankar_001",
        video_url: "https://youtube.com/watch?v=shankar1",
        video_title: "Crypto Market 2023 Predictions",
        video_date: "2023-02-28",
        timestamp_in_video: "05:10",
        exact_quote: "Ethereum will hit 3000 dollars by Q3 2023, the merge effect is underpriced",
        asset_name: "Ethereum",
        asset_type: "crypto",
        predicted_direction: "up",
        predicted_value: 3000,
        predicted_by_date: "2023-09-30",
        confidence_language: "hard_claim",
        actual_value: 1650,
        actual_direction: "down",
        price_on_prediction_date: 1600,
        accuracy_score: 18,
        verdict: "Wrong direction and significantly missed target — ETH fell to 1650 by Q3",
        failure_reason: "Merge benefits already priced in, selling pressure continued",
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "shankar_002",
        video_url: "https://youtube.com/watch?v=shankar2",
        video_title: "Indian Economy Macro Outlook",
        video_date: "2023-01-10",
        timestamp_in_video: "12:00",
        exact_quote: "India GDP growth will disappoint in 2023, we will struggle to hit 6 percent",
        asset_name: "India GDP",
        asset_type: "macro",
        predicted_direction: "down",
        predicted_value: 6,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 7.2,
        actual_direction: "up",
        price_on_prediction_date: null,
        accuracy_score: 12,
        verdict: "Wrong — India grew at 7.2%, one of the fastest major economies in 2023",
        failure_reason: "Underestimated consumption boom and government capex",
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      },
      {
        prediction_id: "shankar_003",
        video_url: "https://youtube.com/watch?v=shankar3",
        video_title: "Stock Picks for 2023",
        video_date: "2023-03-20",
        timestamp_in_video: "08:45",
        exact_quote: "Paytm will recover to 800 rupees as losses narrow through the year",
        asset_name: "Paytm",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: 800,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: 650,
        actual_direction: "up",
        price_on_prediction_date: 540,
        accuracy_score: 52,
        verdict: "Directionally correct but missed 800 target, Paytm closed around 650",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "shankar_004",
        video_url: "https://youtube.com/watch?v=shankar4",
        video_title: "Dollar vs Rupee 2023",
        video_date: "2023-05-05",
        timestamp_in_video: "04:20",
        exact_quote: "Rupee will weaken to 90 against the dollar by year end",
        asset_name: "USD/INR",
        asset_type: "macro",
        predicted_direction: "up",
        predicted_value: 90,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 83,
        actual_direction: "up",
        price_on_prediction_date: 82,
        accuracy_score: 35,
        verdict: "Wrong target — rupee weakened only slightly to 83, not the predicted 90",
        failure_reason: "RBI intervention and strong forex reserves prevented sharp depreciation",
        status: "verified",
        has_disclaimer: false,
        category: "macro"
      },
      {
        prediction_id: "shankar_005",
        video_url: "https://youtube.com/watch?v=shankar5",
        video_title: "Real Estate vs Stocks 2023",
        video_date: "2023-06-25",
        timestamp_in_video: "17:30",
        exact_quote: "Real estate will outperform equities in 2023, people should shift allocation",
        asset_name: "Real Estate",
        asset_type: "macro",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: null,
        accuracy_score: 48,
        verdict: "Partially correct — real estate did well but equities outperformed overall",
        failure_reason: "Stock market rally in H2 exceeded real estate appreciation",
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      }
    ]
  },
  {
    creator_id: "nikhil_kamath",
    creator_name: "Nikhil Kamath",
    overall_accuracy_score: 66,
    total_predictions: 34,
    category_scores: { stocks: 70, crypto: 55, macro: 65, index: 68 },
    predictions: [
      {
        prediction_id: "nikhil_001",
        video_url: "https://youtube.com/watch?v=nikhil1",
        video_title: "Markets in 2023 — My Honest Take",
        video_date: "2023-01-08",
        timestamp_in_video: "06:15",
        exact_quote: "Nifty will deliver double digit returns in 2023, I am very bullish on India",
        asset_name: "Nifty 50",
        asset_type: "index",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 18000,
        accuracy_score: 85,
        verdict: "Correct — Nifty delivered 18% returns in 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "index"
      },
      {
        prediction_id: "nikhil_002",
        video_url: "https://youtube.com/watch?v=nikhil2",
        video_title: "Zerodha's View on Crypto Regulation",
        video_date: "2023-02-14",
        timestamp_in_video: "19:40",
        exact_quote: "Crypto regulation in India will become clearer by mid 2023 and trigger a rally",
        asset_name: "Bitcoin",
        asset_type: "crypto",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-06-30",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 24000,
        accuracy_score: 58,
        verdict: "Partially correct — Bitcoin rallied but regulation clarity never came",
        failure_reason: "Regulatory timeline was optimistic, no major policy announced",
        status: "verified",
        has_disclaimer: true,
        category: "crypto"
      },
      {
        prediction_id: "nikhil_003",
        video_url: "https://youtube.com/watch?v=nikhil3",
        video_title: "Why I Am Buying These 3 Stocks",
        video_date: "2023-03-22",
        timestamp_in_video: "11:30",
        exact_quote: "ICICI Bank is the best positioned private bank and will outperform HDFC Bank in 2023",
        asset_name: "ICICI Bank",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 850,
        accuracy_score: 79,
        verdict: "Correct — ICICI Bank outperformed HDFC Bank by 9% through 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "nikhil_004",
        video_url: "https://youtube.com/watch?v=nikhil4",
        video_title: "Global Recession Fears — Should Indians Worry",
        video_date: "2023-05-30",
        timestamp_in_video: "08:00",
        exact_quote: "Global slowdown will not significantly impact Indian markets, we are decoupled",
        asset_name: "Nifty 50",
        asset_type: "macro",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 18500,
        accuracy_score: 74,
        verdict: "Correct — Indian markets outperformed global peers significantly in 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      },
      {
        prediction_id: "nikhil_005",
        video_url: "https://youtube.com/watch?v=nikhil5",
        video_title: "New Age Tech Stocks — Buy or Avoid",
        video_date: "2023-07-10",
        timestamp_in_video: "23:55",
        exact_quote: "Nykaa and Paytm are value traps, avoid them for at least 12 more months",
        asset_name: "Nykaa",
        asset_type: "stock",
        predicted_direction: "down",
        predicted_value: null,
        predicted_by_date: "2024-07-10",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "down",
        price_on_prediction_date: 148,
        accuracy_score: 71,
        verdict: "Correct — Nykaa remained under pressure and underperformed the broader market",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      }
    ]
  },
  {
    creator_id: "warikoo_harsh",
    creator_name: "Harsh Goela",
    overall_accuracy_score: 44,
    total_predictions: 23,
    category_scores: { stocks: 48, crypto: 30, macro: 44, index: 50 },
    predictions: [
      {
        prediction_id: "harsh_001",
        video_url: "https://youtube.com/watch?v=harsh1",
        video_title: "Top 5 Stocks to Buy in 2023",
        video_date: "2023-01-12",
        timestamp_in_video: "04:50",
        exact_quote: "Adani Group stocks will recover fully within 6 months after Hindenburg report",
        asset_name: "Adani Enterprises",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-07-31",
        confidence_language: "hard_claim",
        actual_value: null,
        actual_direction: "down",
        price_on_prediction_date: 1800,
        accuracy_score: 15,
        verdict: "Wrong — Adani stocks stayed deeply depressed well past July 2023",
        failure_reason: "Underestimated lasting reputational and institutional selling damage",
        status: "verified",
        has_disclaimer: false,
        category: "stocks"
      },
      {
        prediction_id: "harsh_002",
        video_url: "https://youtube.com/watch?v=harsh2",
        video_title: "Mutual Funds vs Direct Stocks",
        video_date: "2023-02-18",
        timestamp_in_video: "16:20",
        exact_quote: "Direct stock picking will beat mutual funds in 2023 for informed investors",
        asset_name: "Nifty 50",
        asset_type: "macro",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: null,
        accuracy_score: 50,
        verdict: "Mixed — some active portfolios beat index but majority of funds matched it",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "macro"
      },
      {
        prediction_id: "harsh_003",
        video_url: "https://youtube.com/watch?v=harsh3",
        video_title: "Is Crypto Worth It in 2023",
        video_date: "2023-03-28",
        timestamp_in_video: "09:10",
        exact_quote: "Dogecoin will hit 1 dollar in 2023 if Elon Musk integrates it into Twitter payments",
        asset_name: "Dogecoin",
        asset_type: "crypto",
        predicted_direction: "up",
        predicted_value: 1,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 0.09,
        actual_direction: "down",
        price_on_prediction_date: 0.08,
        accuracy_score: 5,
        verdict: "Completely wrong — Dogecoin barely moved and Twitter payments never launched",
        failure_reason: "Elon Musk Twitter crypto integration never materialised",
        status: "verified",
        has_disclaimer: false,
        category: "crypto"
      },
      {
        prediction_id: "harsh_004",
        video_url: "https://youtube.com/watch?v=harsh4",
        video_title: "Infrastructure Boom in India",
        video_date: "2023-04-25",
        timestamp_in_video: "13:45",
        exact_quote: "L&T and infrastructure stocks will be the biggest wealth creators of 2023",
        asset_name: "L&T",
        asset_type: "stock",
        predicted_direction: "up",
        predicted_value: null,
        predicted_by_date: "2023-12-31",
        confidence_language: "moderate",
        actual_value: null,
        actual_direction: "up",
        price_on_prediction_date: 2100,
        accuracy_score: 78,
        verdict: "Correct — L&T gained 28% and infrastructure was among top sectors in 2023",
        failure_reason: null,
        status: "verified",
        has_disclaimer: true,
        category: "stocks"
      },
      {
        prediction_id: "harsh_005",
        video_url: "https://youtube.com/watch?v=harsh5",
        video_title: "Rupee Collapse Incoming?",
        video_date: "2023-06-15",
        timestamp_in_video: "07:25",
        exact_quote: "Rupee will crash to 95 against dollar by end of 2023 due to current account deficit",
        asset_name: "USD/INR",
        asset_type: "macro",
        predicted_direction: "up",
        predicted_value: 95,
        predicted_by_date: "2023-12-31",
        confidence_language: "hard_claim",
        actual_value: 83,
        actual_direction: "up",
        price_on_prediction_date: 82,
        accuracy_score: 12,
        verdict: "Wrong — rupee stayed stable around 83, nowhere near predicted 95",
        failure_reason: "Strong RBI management and forex reserves prevented any crash",
        status: "verified",
        has_disclaimer: false,
        category: "macro"
      }
    ]
  }
];